services:
  postgresql:
    image: postgres
    ports: 
    - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgresql
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: malaron2@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

